service: workflow-cost-estimator

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-2
  versionFunctions: false

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  workflow-cost-estimator:
    handler: bin/workflow-cost-estimator
    timeout: 600
    memorySize: 1024
    events:
      - http:
          path: workflow/cost-estimate
          method: get
