service: cse-scripts

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  stage: ${env:SLS_STAGE, 'dev'}
  region: us-east-2
  versionFunctions: false
  tags:
      ce_name: Jacob Johnston
      ce_email: jacobjohnston@gmail.com
      ce_duration: persistent
      ce_purpose: Serverless framework services for CSE provided scripts, workaround, etc. This service create Lambda functions for customers

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  workflow-cost-estimator:
    handler: bin/workflow-cost-estimator
    timeout: 30
    memorySize: 1024
    events:
      - http:
          path: workflow/cost-estimate
          method: get

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: ce-scripts.circleci-support.com
    basePath: 'api'
    stage: ${self:provider.stage}
    createRoute53Record: true
