version: 2.1

references:
    base_image: &base_image circleci/golang:1.12

    working_directory: &working_directory ~/proj

    environment: &environment
        environment:
            GO111MODULE: "on"
            BASH_ENV: /root/.bashrc

    default_settings: &default_settings
        docker:
            - image: *base_image
        working_directory: *working_directory
        <<: *environment

jobs:
    build:
        <<: *default_settings
        steps:
            - checkout
            - run:
                command: |
                    sudo curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
                    sudo apt-get install -y nodejs
                name: install node
            - run: sudo npm i -g serverless
            - run:
                name: set env
                command: |
                    cd && touch $BASH_ENV

                    if [ "${CIRCLE_BRANCH}" == "master" ]; then
                        echo "export SLS_STAGE=prod" | >> $BASH_ENV
                    else
                        export SLS_STAGE=staging
                    fi
            - run:
                  name: Run commit check and BTD
                  command: |
                      source $BASH_ENV
                      ~/proj/.circleci/scripts/commit_check.sh

workflows:
    version: 2.1
    btd:
        jobs:
            - build:
                context: ORB-PUBLISHING

