version: 2.1

references:
    base_image: &base_image circleci/golang:1.12

    working_directory: &working_directory ~/proj

    environment: &environment
        environment:
            GO111MODULE: "on"

    default_settings: &default_settings
        docker:
            - image: *base_image
        working_directory: *working_directory
        <<: *environment

jobs:
    build:
        <<: *default_settings
        steps:
            - checkout
            - run:
                command: |
                    sudo curl -sL https://deb.nodesource.com/setup_12.x | sudo bash -
                    sudo apt-get install -y nodejs
                name: install node
            - run: sudo npm i -g serverless
            - run: ~/proj/.circleci/scripts/commit_check.sh

workflows:
    version: 2.1
    btd:
        jobs:
            build:
                context: ORB-PUBLISHING
